test:
  image: codecr.jlab.org/hallb/clas12/container-forge/analysis
  script:
    - ls -l / /builds
    - cd /builds/touchte/amon/src
    - ls -l .
    - pacman -S -s gtkmm
    - pacman -Syu --noconfirm gtkmm-4.0

  artifacts:
    paths:
      - table.txt

