test:
  image: codecr.jlab.org/hallb/clas12/container-forge/analysis
  script:
    - ls -l / /builds
    - cd /builds/touchte/amon/src
    - ls -l .
    - pacman -S -s gtkmm
    - make
    - echo dog > table.txt
  artifacts:
    paths:
      - table.txt

