#!/bin/bash

export CCDB_CONNECTION="sqlite:////work/clas12/users/touchte/ccdb_2026-04-26.sqlite"

home_dir=/w/hallb-scshelf2102/clas12/users/touchte

#java -cp "$home_dir/coatjava/coatjava/lib/*:$home_dir/amon/java-utils/target/classes" io.github.ftouchte.AhdcAlignmentAnalyser  "$@"
java -cp "$home_dir/amon/java-utils/target/classes:$home_dir/coatjava/coatjava/lib/*:$home_dir/coatjava/coatjava/lib/clas/*:$home_dir/coatjava/coatjava/lib/services/*:$home_dir/coatjava/coatjava/lib/utils/*:/scratch/touchte/tmpfs/maven.m2/org/knowm/xchart/xchart/3.8.8/xchart-3.8.8.jar:/scratch/touchte/tmpfs/maven.m2/de/erichseifert/vectorgraphics2d/VectorGraphics2D/0.13/VectorGraphics2D-0.13.jar:/scratch/touchte/tmpfs/maven.m2/de/rototor/pdfbox/graphics2d/3.0.1/graphics2d-3.0.1.jar:/scratch/touchte/tmpfs/maven.m2/org/apache/pdfbox/pdfbox/3.0.1/pdfbox-3.0.1.jar:/scratch/touchte/tmpfs/maven.m2/org/apache/pdfbox/pdfbox-io/3.0.1/pdfbox-io-3.0.1.jar:/scratch/touchte/tmpfs/maven.m2/org/apache/pdfbox/fontbox/3.0.1/fontbox-3.0.1.jar:/scratch/touchte/tmpfs/maven.m2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/scratch/touchte/tmpfs/maven.m2/org/junit/jupiter/junit-jupiter/5.10.1/junit-jupiter-5.10.1.jar:/scratch/touchte/tmpfs/maven.m2/org/junit/jupiter/junit-jupiter-api/5.10.1/junit-jupiter-api-5.10.1.jar:/scratch/touchte/tmpfs/maven.m2/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar:/scratch/touchte/tmpfs/maven.m2/org/junit/platform/junit-platform-commons/1.10.1/junit-platform-commons-1.10.1.jar:/scratch/touchte/tmpfs/maven.m2/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/scratch/touchte/tmpfs/maven.m2/org/junit/jupiter/junit-jupiter-params/5.10.1/junit-jupiter-params-5.10.1.jar:/scratch/touchte/tmpfs/maven.m2/org/junit/jupiter/junit-jupiter-engine/5.10.1/junit-jupiter-engine-5.10.1.jar:/scratch/touchte/tmpfs/maven.m2/org/junit/platform/junit-platform-engine/1.10.1/junit-platform-engine-1.10.1.jar:/scratch/touchte/tmpfs/maven.m2/com/madgag/animated-gif-lib/1.4/animated-gif-lib-1.4.jar:/scratch/touchte/tmpfs/maven.m2/org/jfree/jfreechart/1.5.6/jfreechart-1.5.6.jar:/scratch/touchte/tmpfs/maven.m2/com/itextpdf/itextpdf/5.5.13.3/itextpdf-5.5.13.3.jar" \
    io.github.ftouchte.kalmanFilter.PerformanceAnalyser "$@"
